#!/usr/bin/env bash
# Generated by generate_network.py from _data/images.yml
# Run locally: bash tools/fetch_images.sh   (then re-run the generator and quarto render)
cd "$(dirname "$0")/../assets/images/network" || exit 1
set -u
[ -f "nist.jpg" ] || curl -sSL -o "nist.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/NIST%20AML%20building.jpg?width=1280" && echo "ok nist"
[ -f "nasa-jpl.jpg" ] || curl -sSL -o "nasa-jpl.jpg" "https://images-assets.nasa.gov/image/PIA25869/PIA25869~large.jpg" && echo "ok nasa-jpl"
[ -f "nasa-gsfc.jpg" ] || curl -sSL -o "nasa-gsfc.jpg" "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001401/GSFC_20171208_Archive_e001401~large.jpg" && echo "ok nasa-gsfc"
[ -f "usgs-spectroscopy.png" ] || curl -sSL -o "usgs-spectroscopy.png" "https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/thumbnails/image/HyperVeg_0.png" && echo "ok usgs-spectroscopy"
[ -f "lbnl-heat-island.jpg" ] || curl -sSL -o "lbnl-heat-island.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Molecular%20Foundry%20at%20Lawrence%20Berkeley%20National%20Laboratory%20(52230758982).jpg?width=1280" && echo "ok lbnl-heat-island"
[ -f "promes-cnrs.jpg" ] || curl -sSL -o "promes-cnrs.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Four-solaire-odeillo-07.jpg?width=1280" && echo "ok promes-cnrs"
[ -f "esa-estec.jpg" ] || curl -sSL -o "esa-estec.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Europe's%20largest%20satellite%20test%20centre.jpg?width=1280" && echo "ok esa-estec"
[ -f "ptb.jpg" ] || curl -sSL -o "ptb.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Luftbild%20Braunschweig%20PTB.jpg?width=1280" && echo "ok ptb"
[ -f "cemhti-cnrs.jpg" ] || curl -sSL -o "cemhti-cnrs.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/200%20MHz%20NMR.jpg?width=1280" && echo "ok cemhti-cnrs"
[ -f "isi-brno.jpg" ] || curl -sSL -o "isi-brno.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Electron%20microscope%20Mamut%20at%20the%20Institute%20of%20Scientific%20Instruments%20of%20the%20Czech%20Academy%20of%20Science%20in%20Brno%20(1).jpg?width=1280" && echo "ok isi-brno"
[ -f "columbia-yu.jpg" ] || curl -sSL -o "columbia-yu.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Northwest%20Corner%20Building,%20Columbia%20University%20(6435263981).jpg?width=1280" && echo "ok columbia-yu"
[ -f "vanderbilt-caldwell.png" ] || curl -sSL -o "vanderbilt-caldwell.png" "https://commons.wikimedia.org/wiki/Special:FilePath/Featheringill%20Hall.png?width=1280" && echo "ok vanderbilt-caldwell"
[ -f "ucla-raman.jpg" ] || curl -sSL -o "ucla-raman.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Boelter%20Hall,%20UCLA.jpg?width=1280" && echo "ok ucla-raman"
[ -f "purdue-ruan.jpg" ] || curl -sSL -o "purdue-ruan.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/BRK%20Wiki2.jpg?width=1280" && echo "ok purdue-ruan"
[ -f "uchicago-hsu.jpg" ] || curl -sSL -o "uchicago-hsu.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/William%20Eckhardt%20Research%20Center,%20University%20of%20Chicago,%20Ellis%20Avenue%20and%2057th%20Street,%20Hyde%20Park,%20Chicago,%20IL%20(54515516675).jpg?width=1280" && echo "ok uchicago-hsu"
[ -f "nanjing-zhu.jpg" ] || curl -sSL -o "nanjing-zhu.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Main%20building%20university%20of%20Nanking%202018.jpg?width=1280" && echo "ok nanjing-zhu"
[ -f "uts-sydney.jpg" ] || curl -sSL -o "uts-sydney.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/UTS%20Tower%202012-08-06.jpg?width=1280" && echo "ok uts-sydney"
[ -f "aist-nmij.jpg" ] || curl -sSL -o "aist-nmij.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/AIST%20Tsukuba%2010.jpg?width=1280" && echo "ok aist-nmij"
[ -f "npl.jpg" ] || curl -sSL -o "npl.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/The%20National%20Physical%20Laboratory,%20Teddington%20-%20geograph.org.uk%20-%204048376.jpg?width=1280" && echo "ok npl"
[ -f "ciemat-psa.jpg" ] || curl -sSL -o "ciemat-psa.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sistema%20de%20Receptor%20central%20con%20campo%20de%20heliostatos,%20Plataforma%20Solar%20de%20Almer%C3%ADa.jpg?width=1280" && echo "ok ciemat-psa"
[ -f "onera-dota.jpg" ] || curl -sSL -o "onera-dota.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/ONERA%20Toulouse.jpg?width=1280" && echo "ok onera-dota"
[ -f "fraunhofer-ise.jpg" ] || curl -sSL -o "fraunhofer-ise.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Fraunhofer%20ISE-Hauptgebaeude.jpg?width=1280" && echo "ok fraunhofer-ise"
