#!/usr/bin/env python3
"""
generate_network.py — single source of truth: _data/institutions.yml

Emits:
  assets/data/labs.json     (map markers + stats; consumed by labs-map.js)
  network/index.qmd         (directory page: map + tier-grouped table)
  network/<id>.qmd          (profiles migrated from the legacy ecosystem,
                             wrapped in the v3 article layout — only when a
                             legacy source exists and no hand-written profile
                             is marked KEEP)

Coordinates live here for now (TODO: fold lat/lon into institutions.yml).
"""
import json, re, sys, html
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
LEGACY = ROOT.parent / "legacy-site" / "ecosystem"
DATA = ROOT / "_data" / "institutions.yml"

COORDS = {
    "ptb": (52.294, 10.461), "cemhti-cnrs": (47.838, 1.944),
    "promes-cnrs": (42.494, 2.029), "cae-wuerzburg": (49.788, 9.953),
    "isi-brno": (49.230, 16.573), "imt-mines-albi": (43.923, 2.141),
    "thermomat-ehu": (43.330, -2.970), "uwb-ntc": (49.726, 13.351),
    "vinca": (44.756, 20.594), "cnr-ino": (43.788, 11.189),
    "nist": (39.137, -77.218), "aist-nmij": (36.054, 140.123),
    "nasa-jpl": (34.201, -118.171), "usgs-spectroscopy": (39.718, -105.073),
    "asu-tes": (33.421, -111.933), "brown-relab": (41.827, -71.400),
    "lten-cnrs": (47.281, -1.518), "stanford-fan": (37.428, -122.169),
    "columbia-yu": (40.810, -73.960), "utah-tift": (40.765, -111.846),
    "vanderbilt-caldwell": (36.144, -86.803), "lbnl-heat-island": (37.875, -122.250),
    "uva": (38.033, -78.508), "ruhr-bochum-leat": (51.446, 7.261),
    "wisconsin-madison": (43.072, -89.400), "lasp-boulder": (40.010, -105.243),
    "dlr-psl": (52.430, 13.530), "npl": (51.427, -0.345),
    "onera-dota": (48.713, 2.230), "fraunhofer-ise": (48.009, 7.833),
    "ciemat-psa": (37.091, -2.358), "esa-estec": (52.218, 4.420),
    "tubitak-ume": (40.790, 29.450), "nasa-gsfc": (38.991, -76.852),
    "ucla-raman": (34.069, -118.445), "purdue-ruan": (40.428, -86.914),
    "uchicago-hsu": (41.790, -87.601), "kaist-jang": (36.372, 127.360),
    "nanjing-zhu": (32.057, 118.778), "uts-sydney": (-33.883, 151.200),
}

TIER_LABEL = {
    "core": "Tier I — Core: emissivity-centred laboratories",
    "extended": "Tier II — Extended: radiative properties among core activities",
    "engineered": "Engineered emissivity: thermal photonics and radiative cooling",
    "emerging": "Emerging and conference-affiliated",
}
TIER_ORDER = ["core", "extended", "engineered", "emerging"]
PILL = {"core": "core", "extended": "", "engineered": "eng", "emerging": ""}


def cap_line(inst):
    c = inst.get("capabilities") or {}
    t, w = c.get("temperature_range_text", ""), c.get("wavelength_range_text", "")
    bits = [b for b in (w, t) if b]
    if bits:
        return " · ".join(bits)
    note = (c.get("methodology_notes") or "").strip()
    return (note[:130] + "…") if len(note) > 130 else note


IMAGES = {}
IMG_DIR = ROOT / "assets" / "images" / "network"


def load_images():
    global IMAGES
    f = ROOT / "_data" / "images.yml"
    if f.exists():
        IMAGES = (yaml.safe_load(f.read_text()) or {}).get("images", {}) or {}


def figure_block(iid):
    """Raw-HTML figure for an institution, only if the image file is
    actually present locally (run tools/fetch_images.sh first)."""
    img = IMAGES.get(iid)
    if not img:
        return ""
    ext = ".png" if img["direct_url"].split("?")[0].lower().endswith(".png") else ".jpg"
    if not (IMG_DIR / f"{iid}{ext}").exists():
        return ""
    cap = html.escape(img.get("caption", ""))
    credit = html.escape(img.get("credit", ""))
    lic_page = img.get("license_page", "")
    return f"""
```{{=html}}
<figure class="lab-photo">
  <img src="/assets/images/network/{iid}{ext}" alt="{cap}" loading="lazy" />
  <figcaption>{cap} <a href="{lic_page}">{credit}</a>.</figcaption>
</figure>
```
"""


def write_fetch_script():
    """Emit tools/fetch_images.sh — run it on your own machine to download
    the license-verified images into assets/images/network/."""
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by generate_network.py from _data/images.yml",
        "# Run locally: bash tools/fetch_images.sh   (then re-run the generator and quarto render)",
        'cd "$(dirname "$0")/../assets/images/network" || exit 1',
        "set -u",
    ]
    for iid, img in IMAGES.items():
        ext = ".png" if img["direct_url"].split("?")[0].lower().endswith(".png") else ".jpg"
        lines.append(f'[ -f "{iid}{ext}" ] || curl -sSL -o "{iid}{ext}" "{img["direct_url"]}" && echo "ok {iid}"')
    (ROOT / "tools" / "fetch_images.sh").write_text("\n".join(lines) + "\n")
    print(f"tools/fetch_images.sh written ({len(IMAGES)} images)")


def profile_from_yaml(i, stats):
    """Build a profile page directly from the institutions.yml entry.
    Used for entries added after the legacy era — the YAML is the single
    source of truth and carries the verified prose."""
    title = i.get("short_name", i["id"])
    name = i["name"]
    eco = (i.get("ecosystem_primary") or "").replace("_", " ").title()
    units_rows = "\n".join(
        f"| **Unit** | [{u['name']}]({u['url']}) |" if u.get("url") else f"| **Unit** | {u['name']} |"
        for u in (i.get("units") or [])
    )
    people = " · ".join(p["name"] for p in (i.get("people") or []))
    people_row = f"| **Publicly linked people** | {people} |" if people else ""
    db = " · ".join(i.get("databases_hosted") or [])
    db_row = f"| **Databases hosted** | {db} |" if db else ""
    c = i.get("capabilities") or {}
    cap_rows = []
    if i.get("properties_measured"):
        cap_rows.append("- **Quantities:** " + " · ".join(i["properties_measured"]))
    if c.get("wavelength_range_text"):
        cap_rows.append(f"- **Spectral range:** {c['wavelength_range_text']}")
    if c.get("temperature_range_text"):
        cap_rows.append(f"- **Temperature:** {c['temperature_range_text']}")
    if c.get("methodology_notes"):
        cap_rows.append(f"- **Methodology:** {c['methodology_notes']}")
    apps = " · ".join(i.get("applications") or [])
    sources = "\n".join(f"- [{s['label']}]({s['url']})" for s in (i.get("external_sources") or []))
    why = (i.get("why_it_matters") or "").strip()
    return f"""---
title: "{title}"
page-layout: full
toc: false
---

<!-- generated-from: institutions.yml — do not edit by hand; edit the YAML and re-run tools/generate_network.py -->

```{{=html}}
<div class="crumbs"><a href="/network/index.html">Network</a> / <a href="/network/index.html">Research map</a> / {html.escape(title)}</div>
```

::: {{.page-article}}
# {name}
{figure_block(i["id"])}
## Snapshot

| | |
|---|---|
| **Country** | {i['country']} |
| **City** | {i['city']} |
| **Tier** | {i['tier'].capitalize()} |
| **Primary ecosystem** | {eco} |
{units_rows}
{people_row}
{db_row}

## Why it matters internationally

{why}

## Scope of activity

{chr(10).join(cap_rows)}

**Application domains:** {apps}.

## External sources

{sources}

::: {{.sources-panel}}
### Traceability

Every claim in this profile traces to the external sources listed above.
Profile follows the [research-map methodology](/network/methodology.html).
Added to the directory: {stats['data_revision']} (verified against the
institution's public pages or peer-reviewed publications).
:::

:::
"""


def main():
    doc = yaml.safe_load(DATA.read_text())
    insts = doc["institutions"]
    meta = doc.get("meta", {})
    load_images()
    IMG_DIR.mkdir(parents=True, exist_ok=True)
    write_fetch_script()

    countries = sorted({i["country"] for i in insts})
    stats = {
        "institutions": len(insts),
        "countries": len({i["iso_country"] for i in insts}),
        "core": sum(1 for i in insts if i["tier"] == "core"),
        "ecosystems": len(meta.get("ecosystems", {})),
        "countries_list": countries,
        "data_revision": "2026-06-11",
    }

    # ---------- labs.json ----------
    labs = []
    for i in insts:
        if i["id"] not in COORDS:
            print(f"WARN: no coordinates for {i['id']} — skipped on map", file=sys.stderr)
            continue
        lat, lon = COORDS[i["id"]]
        labs.append({
            "id": i["id"], "name": i["name"], "short": i.get("short_name", i["id"]),
            "city": i.get("city", ""), "country": i.get("country", ""),
            "iso": i.get("iso_country", ""), "tier": i["tier"],
            "lat": lat, "lon": lon, "url": f"/network/{i['id']}.html",
        })
    out = ROOT / "assets" / "data"
    out.mkdir(parents=True, exist_ok=True)
    (out / "labs.json").write_text(json.dumps({"stats": stats, "labs": labs}, indent=1))
    print(f"labs.json: {len(labs)} markers")

    # ---------- network/index.qmd ----------
    rows_by_tier = {t: [] for t in TIER_ORDER}
    for i in sorted(insts, key=lambda x: (TIER_ORDER.index(x["tier"]), x.get("rank", 999))):
        unit = (i.get("units") or [{}])[0].get("name", "")
        pill_cls = PILL[i["tier"]]
        pill = f'<span class="tier-pill {pill_cls}">{i["tier"]}</span>'
        rows_by_tier[i["tier"]].append(f"""        <tr>
          <td class="inst"><a href="/network/{i['id']}.html">{html.escape(i['name'])}</a>
            <span class="unit">{html.escape(unit)}</span></td>
          <td class="cc">{i['iso_country']}</td>
          <td>{pill}</td>
          <td class="cap">{html.escape(cap_line(i))}</td>
        </tr>""")

    tier_blocks = []
    for t in TIER_ORDER:
        if not rows_by_tier[t]:
            continue
        tier_blocks.append(f"""    <h3 class="dir-tier">{TIER_LABEL[t]}</h3>
    <table class="dir">
      <thead><tr><th>Institution</th><th>Country</th><th>Tier</th><th class="cap">Capability envelope</th></tr></thead>
      <tbody>
{chr(10).join(rows_by_tier[t])}
      </tbody>
    </table>""")

    countries_line = " · ".join(countries)
    network_index = f"""---
title: "Research map"
page-layout: full
toc: false
---

```{{=html}}
<section class="home-section" style="border-bottom:none; padding-top:40px;">
  <div class="wrap">
    <div class="sec-head">
      <h2>The research map</h2>
      <a class="more" href="/network/methodology.html">Methodology →</a>
    </div>
    <p class="sec-intro">
      The curated directory of non-commercial institutions where emissivity and
      thermal radiative properties are actively researched. Inclusion criteria,
      tier logic, and limitations are documented in the
      <a href="/network/methodology.html">methodology</a>; corrections and
      additions go through the <a href="/contribute/index.html">editorial board</a>.
      Directory revision: {stats['data_revision']}.
    </p>

    <div class="net-stats">
      <div class="net-stat"><div class="v">{stats['institutions']}</div><div class="k">institutions</div></div>
      <div class="net-stat"><div class="v">{stats['countries']}</div><div class="k">countries</div></div>
      <div class="net-stat"><div class="v">{stats['core']}</div><div class="k">core-tier laboratories</div></div>
      <div class="net-stat"><div class="v">{stats['ecosystems']}</div><div class="k">thematic ecosystems</div></div>
    </div>

    <div id="labmap" class="labmap labmap-tall" aria-label="World map of institutions on the research map"></div>
    <div class="map-legend">
      <span class="key"><span class="dot meas"></span> Measurement &amp; metrology laboratories</span>
      <span class="key"><span class="dot eng"></span> Engineered emissivity (thermal photonics, radiative cooling)</span>
      <span class="note">Markers link to institution profiles.</span>
    </div>

{chr(10).join(tier_blocks)}

    <p class="countries">{countries_line}</p>
  </div>
</section>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js"></script>
<script src="../assets/scripts/labs-map.js"></script>
```
"""
    nd = ROOT / "network"
    nd.mkdir(exist_ok=True)
    (nd / "index.qmd").write_text(network_index)
    print("network/index.qmd written")

    # ---------- migrate legacy profiles ----------
    HAND_WRITTEN = {"dlr-psl", "npl"}  # authored directly in network/, do not overwrite
    migrated = 0
    for i in insts:
        iid = i["id"]
        if iid in HAND_WRITTEN:
            continue
        src = LEGACY / "institutions" / f"{iid}.qmd"
        if not src.exists():
            # No legacy source (standalone repo, or a new entry).
            # Preserve committed profiles unless they carry the
            # generated-from marker; (re)generate from YAML otherwise.
            (nd := ROOT / "network").mkdir(exist_ok=True)
            target = nd / f"{iid}.qmd"
            if target.exists() and "generated-from: institutions.yml" not in target.read_text():
                continue  # authoritative committed profile — keep it
            target.write_text(profile_from_yaml(i, stats))
            migrated += 1
            continue
        text = src.read_text()
        m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
        if not m:
            print(f"WARN: cannot parse {src}", file=sys.stderr)
            continue
        fm = yaml.safe_load(m.group(1))
        body = m.group(2).strip()
        title = fm.get("title", i["name"])
        short = fm.get("short-name", i.get("short_name", iid))
        profile = f"""---
title: "{title}"
page-layout: full
toc: false
---

```{{=html}}
<div class="crumbs"><a href="/network/index.html">Network</a> / <a href="/network/index.html">Research map</a> / {html.escape(short)}</div>
```

::: {{.page-article}}
# {title}
{figure_block(iid)}
{body}

::: {{.sources-panel}}
### Traceability

Every claim in this profile traces to the external sources listed above.
Profile follows the [research-map methodology](/network/methodology.html).
Last verified: 2026-04 (directory revision {stats['data_revision']}).
:::

:::
"""
        (nd / f"{iid}.qmd").write_text(profile)
        migrated += 1
    print(f"profiles migrated: {migrated}")

    # ---------- methodology + ecosystems ----------
    for name in ("methodology", "ecosystems"):
        src = LEGACY / f"{name}.qmd"
        if not src.exists():
            continue
        text = src.read_text()
        m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
        fm = yaml.safe_load(m.group(1))
        body = m.group(2).strip()
        # legacy cross-links -> new section URLs
        body = (body.replace("(directory.qmd)", "(/network/index.html)")
                    .replace("(ecosystems.qmd)", "(/network/ecosystems.html)")
                    .replace("(methodology.qmd)", "(/network/methodology.html)")
                    .replace("(index.qmd)", "(/network/index.html)"))
        title = fm.get("title", name.title())
        page = f"""---
title: "{title}"
page-layout: full
toc: false
---

```{{=html}}
<div class="crumbs"><a href="/network/index.html">Network</a> / {html.escape(title)}</div>
```

::: {{.page-article}}
# {title}

{body}
:::
"""
        (nd / f"{name}.qmd").write_text(page)
        print(f"network/{name}.qmd written")


if __name__ == "__main__":
    main()
