#!/usr/bin/env python3
"""generate_changelog.py — renders the site changelog and release notes.

Reads   _data/changelog.yml   (additions, for the community)
        _data/releases.yml    (release notes, for maintainers)
Writes  changelog.qmd                 → /changelog.html  ("What's new")
        about/release-notes.qmd       → /about/release-notes.html
        assets/includes/site-footer.html  (only the region between
                                           <!-- updated:start --> and
                                           <!-- updated:end -->)

The footer stamp shows the newest date found in either file. Run after
editing either YAML, then quarto render. Runs in tools/netlify-build.sh.
"""
import html
from collections import OrderedDict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG = ROOT / "_data" / "changelog.yml"
RELEASES = ROOT / "_data" / "releases.yml"
OUT_CHANGELOG = ROOT / "changelog.qmd"
OUT_RELEASES = ROOT / "about" / "release-notes.qmd"
FOOTER = ROOT / "assets" / "includes" / "site-footer.html"

KIND_LABEL = {
    "content": "Content",
    "data": "Data",
    "feature": "Feature",
    "fix": "Fix",
    "editorial": "Editorial",
}

e = html.escape


def load(path, key):
    with open(path, encoding="utf-8") as f:
        items = yaml.safe_load(f).get(key, []) or []
    items.sort(key=lambda x: str(x["date"]), reverse=True)
    return items


def links_html(links):
    if not links:
        return ""
    parts = [f'<a href="{e(l["url"])}">{e(l["label"])}</a>' for l in links]
    return ' <span class="sep">·</span> '.join(parts)


def render_changelog(entries, newest):
    by_date = OrderedDict()
    for en in entries:
        by_date.setdefault(str(en["date"]), []).append(en)

    out = []
    out.append("---\n")
    out.append('title: "What\'s new"\n')
    out.append("page-layout: full\ntoc: false\n---\n\n")
    out.append("```{=html}\n")
    out.append("<!-- GENERATED by tools/generate_changelog.py from _data/changelog.yml — do not edit -->\n")
    out.append('<div class="inner-page">\n')
    out.append('  <p class="section-label">Site</p>\n')
    out.append("  <h1>What's new on emissivity.org</h1>\n")
    out.append(
        '  <p class="inner-page__subtitle">Every addition to the site, newest first: '
        "pages, news, datasets, map entries and features. Last updated "
        f"{e(newest)}. Maintainers' notes on how each release was built are in the "
        '<a href="/about/release-notes.html">release notes</a>.</p>\n'
    )
    for date, group in by_date.items():
        out.append(f'  <h2 class="log-date">{e(date)}</h2>\n')
        for en in group:
            kind = KIND_LABEL.get(en.get("kind", ""), "Change")
            out.append('  <div class="log-entry">\n')
            out.append(f'    <span class="log-kind">{e(kind)}</span>\n')
            out.append(f'    <div class="log-title">{e(en["title"])}</div>\n')
            if en.get("summary"):
                out.append(f'    <p class="log-summary">{e(en["summary"])}</p>\n')
            meta = links_html(en.get("links"))
            if en.get("commit"):
                meta += (' <span class="sep">·</span> ' if meta else "") + f'<span class="log-commit">{e(en["commit"])}</span>'
            if meta:
                out.append(f'    <p class="log-meta">{meta}</p>\n')
            out.append("  </div>\n")
    out.append("</div>\n```\n")
    OUT_CHANGELOG.write_text("".join(out), encoding="utf-8")


def render_releases(releases, newest):
    out = []
    out.append("---\n")
    out.append('title: "Release notes"\n')
    out.append("page-layout: full\ntoc: false\n---\n\n")
    out.append("```{=html}\n")
    out.append("<!-- GENERATED by tools/generate_changelog.py from _data/releases.yml — do not edit -->\n")
    out.append('<div class="inner-page">\n')
    out.append('  <p class="section-label">Site</p>\n')
    out.append("  <h1>Release notes</h1>\n")
    out.append(
        '  <p class="inner-page__subtitle">How emissivity.org is built and what changed in each '
        "release, written for whoever maintains the site next. Additions visible to visitors are "
        f'listed on <a href="/changelog.html">What\'s new</a>. Last updated {e(newest)}.</p>\n'
    )
    out.append(
        "  <p>The site is a Quarto website deployed by Netlify from the <code>main</code> branch. "
        "Data-driven pages are generated at build time from the YAML files in <code>_data/</code> by "
        "the scripts in <code>tools/</code>; the build order is in <code>tools/netlify-build.sh</code>. "
        "The repository README lists every data source and the routine maintenance commands.</p>\n"
    )
    for r in releases:
        out.append('  <div class="release">\n')
        out.append(f'    <h2><span class="release-version">{e(r["version"])}</span> {e(r["title"])} <span class="log-date-inline">{e(str(r["date"]))}</span></h2>\n')
        if r.get("changes"):
            out.append("    <h3>What changed</h3>\n    <ul>\n")
            out.extend(f"      <li>{e(c)}</li>\n" for c in r["changes"])
            out.append("    </ul>\n")
        if r.get("how"):
            out.append("    <h3>How it was done</h3>\n    <ul>\n")
            out.extend(f"      <li>{e(c)}</li>\n" for c in r["how"])
            out.append("    </ul>\n")
        if r.get("files"):
            out.append("    <h3>Files to know</h3>\n    <ul class=\"release-files\">\n")
            out.extend(f"      <li><code>{e(c)}</code></li>\n" for c in r["files"])
            out.append("    </ul>\n")
        out.append("  </div>\n")
    out.append("</div>\n```\n")
    OUT_RELEASES.write_text("".join(out), encoding="utf-8")


def stamp_footer(newest):
    text = FOOTER.read_text(encoding="utf-8")
    start, end = "<!-- updated:start -->", "<!-- updated:end -->"
    i, j = text.find(start), text.find(end)
    if i < 0 or j < 0:
        raise SystemExit("site-footer.html: updated:start/end markers not found")
    stamp = (
        f'{start}<span class="site-updated">Last updated {e(newest)} · '
        f'<a href="/changelog.html">What\'s new →</a></span>{end}'
    )
    FOOTER.write_text(text[:i] + stamp + text[j + len(end):], encoding="utf-8")


def main():
    entries = load(CHANGELOG, "entries")
    releases = load(RELEASES, "releases")
    dates = [str(x["date"]) for x in entries] + [str(x["date"]) for x in releases]
    newest = max(dates) if dates else "—"
    render_changelog(entries, newest)
    render_releases(releases, newest)
    stamp_footer(newest)
    print(f"changelog: {len(entries)} entries, {len(releases)} releases, last updated {newest}")


if __name__ == "__main__":
    main()
